### PR TITLE
Move attack parameters from `init` to `fit` method

### LINKED ISSUE #190: Explain why training and test set both have to be passed into the attack

### PR DESCRIPTION
**Pull request by marisanest**
Closes #190.

### CODE REVIEW

**Review by Erdnaf — APPROVED** [review]
Looks very good 👍 much cleaner attack interface.
I saw you also changed the code of `Team 2` slightly.
maybe we should tell them?

**Review by budmil — APPROVED** [review]

**Comment by Friedrich-Mueller** [comment]
Heyhey, I came across an issue when running the notebooks locally:

ValueError: Found input variables with inconsistent numbers of samples: [200, 400]

happens during the rule based as well as the decision boundary attack during the attack analysis. Specifically its complaining about the 'slicing' argument in it.

I tried looking into it but couldnt make sense of it on the fly, ill look into it a bit later again, if noone else is faster :)

**Comment by marisanest** [comment]
I just tested everything again in Colab. It's working for me. Maybe you have some diverging versions locally!? Have you tried it with Colab already? I only have a problem with the HotSkipJump. It takes quite a long time again and at the moment for the `MembershipInferenceAttackAnalysis` there is no possibility to add the `max_iter, max_eval, init_eval` parameters to make it a bit faster. We should definitely change that.

**Comment by marisanest** [comment]
@Erdnaf it's just really a small change in their code. I removed the `None` values they entered as a work-around. But yes, maybe we just inform them really short in their chat.

**Comment by marisanest** [comment]
@Friedrich-Mueller ok after waiting quite a while, I now get the same error. I am also not sure what's happening at the moment and I do not have the time to look into it right now. But it seems that it has something to do with the slicing so maybe @jtorhoff can help.

**Comment by jtorhoff** [comment]
Hey, it's due to the `probabilities` parameter of the `attack` method. I didn't interpret the return values of ART in my initial implementation correctly. I will push a fix shortly.

**Review by jtorhoff — APPROVED** [review]

**Comment by jtorhoff** [comment]
> I just tested everything again in Colab. It's working for me. Maybe you have some diverging versions locally!? Have you tried it with Colab already? I only have a problem with the HotSkipJump. It takes quite a long time again and at the moment for the `MembershipInferenceAttackAnalysis` there is no possibility to add the `max_iter, max_eval, init_eval` parameters to make it a bit faster. We should definitely change that.

I just created an issue for that, I'll look into changing the API a bit to make it more flexible #222. I think this PR can be merged now.

**Comment by Friedrich-Mueller** [comment]
> > I just tested everything again in Colab. It's working for me. Maybe you have some diverging versions locally!? Have you tried it with Colab already? I only have a problem with the HotSkipJump. It takes quite a long time again and at the moment for the `MembershipInferenceAttackAnalysis` there is no possibility to add the `max_iter, max_eval, init_eval` parameters to make it a bit faster. We should definitely change that.
> 
> I just created an issue for that, I'll look into changing the API a bit to make it more flexible #222. I think this PR can be merged now.

Ill run through the notebooks real quick again and then will merge it
Thanks for the fix, juri

**Pull request merged**
