### PR TITLE
Add On Point Basis description to readme

### PR DESCRIPTION
**Pull request by blauertee**

### CODE REVIEW

**Review by Erdnaf — APPROVED** [review]

**Review by marisanest — CHANGES_REQUESTED** [review]
Would be great if you might use some of the wording of the other descriptions (e.g. *"This is the implementation of the original idea ..."*, etc.) and integrate the notation _(X,y)<sub>target</sub>_. Then I can also add a table about the used datasets like for the other attacks. I know we discussed this and said it might not be needed but I think it would be nice to have.

**Comment by Erdnaf** [comment]
> Would be great if you might use some of the wording of the other descriptions (e.g. _"This is the implementation of the original idea ..."_, etc.) and integrate the notation _(X,y)target_. Then I can also add a table about the used datasets like for the other attacks. I know we discussed this and said it might not be needed but I think it would be nice to have.

Maybe add a scentece like `the attack is generaly done with data of _(X,y)target_ to see if one datapoint or a specific class is vounrable.`

As a table maybe quite the same table as in Membership Inference Black-Box Rule-Based

**Comment by Erdnaf** [comment]
I noticed this PR then would also close #198 since there is only the last bullet point missing on that

**Review by marisanest — APPROVED** [review]
Perfecto, thanks :+1:

**Pull request merged**
