### PR TITLE
Finalize project

### LINKED ISSUE #201: Finalizing the project
- do a cleanup
- check for consistency everywhere

### PR DESCRIPTION
**Pull request by Erdnaf**
closes #201

### CODE REVIEW

**Comment by Friedrich-Mueller** [comment]
I got this error: https://stackoverflow.com/questions/64862818/cannot-import-name-png-from-matplotlib
So I changed the matplotlib version according to this thread. I am not sure if this exact version is the best choice, but for now it fixes that error. Maybe someone else can comment on that?

**Comment by Friedrich-Mueller** [comment]
The wrong colab notebook filename of the on point basis attack (privacy score) is actually a known issue, see here: https://github.com/googlecolab/colabtools/issues/764. Just for everyones info

**Comment by Erdnaf** [comment]
> 
> 
> I got this error in the privacy score colab notebook: https://stackoverflow.com/questions/64862818/cannot-import-name-png-from-matplotlib
> So I changed the matplotlib version according to this thread. I am not sure if this exact version is the best choice, but for now it fixes that error. Maybe someone else can comment on that?

I Testet the on point notebook localy, seems fine with the version change, i see no issues there

Can we merge this now so all changes are on `team1sprint6`?

**Review by jtorhoff — APPROVED** [review]

**Review by marisanest — APPROVED** [review]
Looks perfect, I think we can merge the branch and let Franziska know that she can start with the review.

**Pull request merged**
