### PR TITLE
Style: Switch to local imports

### PR DESCRIPTION
**Pull request by blauertee**
Solves  #111

### CODE REVIEW

**Comment by blauertee** [comment]
Not sure weather the branch I did the PR from was in the right state some of the lines that changed in the diff have nothing to do with the import's. Maybe @marisanest you know what's going on there?

**Review by marisanest — CHANGES_REQUESTED** [review]
I found some imports which are still not relative (e.g. in [membership_inference.py](https://github.com/blauertee/privacy-evaluator/blob/style-111-switch-to-local-imports/privacy_evaluator/attacks/membership_inference/membership_inference.py) you have `from privacy_evaluator.metrics.basics import ...`). To find all remaining imports you can simply search for `privacy_evaluator.` in the `privacy_evaluator` folder.

**Review by Erdnaf — APPROVED** [review]
Tested the instalation and now all I imports are relative 👍

**Review by marisanest — APPROVED** [review]
Same here. So I will merge the PR due to 2 accepted Reviews.

**Review by jtorhoff — APPROVED** [review]

**Pull request merged**
