### PR TITLE
Implementation of MIA and Metrics (Precision, Recall)

### PR DESCRIPTION
**Pull request by Friedrich-Mueller**
Solves issues #8 and #50

### CODE REVIEW

**Comment by marisanest** [comment]
Please do not merge yet, there are still some open todos in the code.

**Comment by marisanest** [comment]
Also solves issue#40.

**Review by Erdnaf — APPROVED** [review]

**Review by jtorhoff — APPROVED** [review]

**Comment by marisanest** [comment]
Also solves issues #41 and #53.

**Review by marisanest — APPROVED** [review]

**Review by budmil — APPROVED** [review]

**Comment by Friedrich-Mueller** [comment]
It might be a bit late to ask, and please forgive my lack of experience, but should we really bundle all this into this single PR? My initial intention was to post the contents of the notebook we got from Franziska, just as a starting point for further improvements. I guess it served its purpose that way, but I wasnt expecting so much work on this single PR :)
Tbh, I kind of lost overview too, as well as the ability to "review" :(

**Comment by marisanest** [comment]
@Friedrich-Mueller of course, you could split these PRs into multiple PRs but all solved issues within this PR are related so normally that's totally fine. And I did most of the commits in one day, so it was just a bit inefficient for me to open one PR for a subtask and then wait days until I can go on. I also explained the code in our meeting. I will just merge this PR for now.

**Comment by marisanest** [comment]
@budmil we probably need to adjust the GitHub Actions again. Locally everything is fine, it's just again the importing which is not working. I think we need something like a `setup.py` file in order to correctly build the `privacy-evaluator` package for the tests.

**Comment by marisanest** [comment]
Ok, I think the problem is that ART is not properly installed on the test server. @budmil can you please check if you install the requirements properly

**Comment by budmil** [comment]
I'm on it

**Comment by budmil** [comment]
@marisanest hmm the problem is indeed the requirements/dependencies. 

I am not sure how forking works and @Friedrich-Mueller's branch is forked, so I pushed change directly into branch team1sprint2. I thought that would trigger GitHub Actions to run again, but apparently it does not. Can someone try to just copy-paste those changes from testing.yml into Friedrich's fork or?

**Comment by Friedrich-Mueller** [comment]
Im not sure if I understand the problem. Lets talk about it tomorrow morning?

**Comment by marisanest** [comment]
@budmil great thanks, I will merge it into @Friedrich-Mueller's branch now, then it should recheck.

**Comment by budmil** [comment]
yaay looks good

**Pull request merged**
