### PR TITLE
Add dataset description table to `README`

### LINKED ISSUE #191: table in readme to solve confusion between target and atack model with purpose and data they have seen
also what training arguments the users/functions have access to

### PR DESCRIPTION
**Pull request by marisanest**
Closes #191.

### CODE REVIEW

**Comment by marisanest** [comment]
Do not merge yet, I want to wait till this pull request [230](https://github.com/privML/privacy-evaluator/pull/230) is done so that I might add a table for this attack as well.

**Review by Erdnaf — APPROVED** [review]
Looks good 👍

**Comment by Friedrich-Mueller** [comment]
Heyhey, thanks for the great work @marisanest. I allowed myself to improve a little upon it, as the issue stated something related to "purpose", in addition to the data set information. So I tried to incorporate that. Let me know what you think. Since the table for the first two attacks is identical, I once again thought about moving the 3 tables to the introduction of the MIA attacks, but I couldn't come up with an elegant merge of the tables, so I left them there. I think its fine if they are split like that.

**Comment by Friedrich-Mueller** [comment]
can we merge this?

**Comment by marisanest** [comment]
Yes, I just added a table for `MembershipInferenceAttackOnPointBasis` after Jakob now changed the README accordingly. Can you please check it again @Friedrich-Mueller? And I also changed the description a tiny bit, so @blauertee, could you also have a look? If everything is fine we can merge.

**Comment by Friedrich-Mueller** [comment]
> Yes, I just added a table for `MembershipInferenceAttackOnPointBasis` after Jakob now changed the README accordingly. Can you please check it again @Friedrich-Mueller? And I also changed the description a tiny bit, so @blauertee, could you also have a look? If everything is fine we can merge.

The table LGTM

**Comment by marisanest** [comment]
Ok, I checked the implementation again, and it seems that indeed both datasets are needed, although I can't say clearly why. So I will keep the changes I added in the `README` and merge them for now.

**Pull request merged**
