### PR TITLE
Privacy risk score in slicing 

### LINKED ISSUE #199: Privacy risk score in slicing
- output a distribution of the points for each slice
- also the average score on each slice in a histogram

### PR DESCRIPTION
**Pull request by Erdnaf**
closes #199

### CODE REVIEW

**Comment by Erdnaf** [comment]
Hey i added some code to plot the data.
`histogram_distribution` is for Ploting whihtiin the slices and
`histogram_slices` for the summary of all slices

`histogram_slices` actualy does not use any variables of the object, so you can also call it independent from them. Maybe move that to a helper function and not call whition the object?

**Comment by budmil** [comment]
I think it would be more consistent to keep it this way. Also, logically it makes sense.

**Comment by jtorhoff** [comment]
I'm not sure how to implement it with the way slicing is working now through the MembershipInferenceAttackAnalysis.

**Comment by Erdnaf** [comment]
I imagined that when computing the slcices you call `histogram_distribution` on the output to get the histogram drawn for each slice.
and wehnn all the slices are computed there is `histogram_slices` called with the avereges of each slice (has to be computed) and the slice names.
If something is unclaes we can also colaborate on this just message me

**Comment by jtorhoff** [comment]
I put some ✨ finishing touches ✨  and fixed the plots. @Erdnaf should we merge so that others don't have to wait bc of notebooks?

**Comment by Erdnaf** [comment]
Hey great work! I Just made some last small changes. I think the progress can be merged if one other person reviews 😁

**Review by marisanest — APPROVED** [review]
Looks perfect :tada: 

I just had a problem with an import in the notebook. It seems that whenever we do something like `import privacy_evaluator.[...]` in the notebooks the whole codebase is loaded. It has to do with how we do the importing in the `__init__` files. It seems that we still do not do it the right way :cry: 

So what happened is that the code of `team2` was also loaded and the line `from tqdm.contrib.logging import logging_redirect_tqdm` did not work for me. But nevertheless, it does not have anything to do with your code and it seems I am the only person who has this problem, so never mind.

**Comment by jtorhoff** [comment]
> So what happened is that the code of `team2` was also loaded and the line `from tqdm.contrib.logging import logging_redirect_tqdm` didn't work for me. But nevertheless, it doen't have anything to do with your code and it seems I am the only person who has this problem, so never mind.

I'm curious what the exact error was? Maybe you can run `pip install -e .` again. I think I needed it too when `tqdm` was added as a dependency. 

> I just had a problem with an import in the notebook. It seems that whenever we do something like `import privacy_evaluator.[...]` in the notebooks the whole codebase is loaded. It has something to do with our importing in the `__init__` files. It seems that we still don't do it the right way 😢

This actually might be common and normal but I'm not sure. I think I've noticed several times myself when I import `torch` or `tensorflow` the import statement alone might take a while to execute.

**Pull request merged**
